name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: rdgallagher/ssp-vst:latest
  
  build:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - uses: actions/checkout@v2
      - run: docker run --rm rdgallagher/ssp-vst > dockcross
      - run: chmod +x dockcross
      - run: ./dockcross bash -c 'cd plugins/scp/Builds/Linux && make CONFIG=Release'
